#!/usr/bin/env python

import argparse

import gtk
import gobject
from widgets import login
from widgets.uiwindow import UIFrame

if __name__ == '__main__':
	parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter,description='RTS2 GTK UI')
	parser.add_argument('forms',help='forms',type=str,nargs='+')

	args = parser.parse_args()

	gobject.threads_init()
	l = login.Login()
	l.signon()

	frame = UIFrame(login.getProxy(), args.forms[0])

	w = gtk.Window()
	w.add(frame)
	w.connect('destroy',gtk.main_quit)
	w.show_all()
	gtk.main()
