#!/usr/bin/python

import gettext
import uiwindow
import uitable
import gtk
import login
import pointing

t = gettext.translation('rts2',fallback=True)
_ = t.lgettext

l = login.Login()
l.signon()

w = uiwindow.UIWindow(None)
w.set_title(_('Chase 500 control'))
t = uitable.UITable(1,1)

t.attach(gtk.Label('RA_X'),0,1,0,1)
t.attach(uiwindow.Label('LIMITS','RA_X'),1,2,0,1)

t.attach(gtk.Label('ZENITH_ANGLE'),0,1,1,2)
t.attach(uiwindow.Label('LIMITS','ZENITH_ANGLE'),1,2,1,2)

t.attach(gtk.Label('MOUNT_PROTECTED'),0,1,2,3)
t.attach(uiwindow.ToggleButton('LIMITS','MOUNT_PROTECTED'),1,2,2,3)

t.attach(uiwindow.SelectionComboEntry('T0','guide_rate'),0,2,3,4,gtk.EXPAND | gtk.SHRINK | gtk.FILL, gtk.EXPAND | gtk.SHRINK)

t.attach(uiwindow.SelectionComboEntry('T0','center_rate'),0,2,4,5,gtk.EXPAND | gtk.SHRINK | gtk.FILL, gtk.EXPAND | gtk.SHRINK)

t.attach(pointing.Pointing(show_multipliers=False),2,3,0,5)

w.add(t)
w.start_push()
w.show_all()

w.connect('destroy', gtk.main_quit)
gtk.main()
